name: "Build Docker Image"
description: "Build a Docker image for the specified Dockerfile"

inputs:
  dockerfile:
    description: "Path to the Dockerfile"
    required: true
  image_name:
    description: "Docker image name"
    required: true
  tag:
    description: "Tag to use for the Docker image"
    required: true
    type: string
  dev:
    description: "Whether to add a 'dev' tag"
    required: false
    default: "false"
    type: boolean
  shouldRelease:
    description: "Whether to release the Docker image in the registry"
    required: false
    default: "false"
    type: boolean
  DOCKER_USERNAME:
    description: "Docker username"
    required: true
    type: string
  DOCKER_PASSWORD:
    description: "Docker password"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image with main tag
      shell: bash
      run: docker build -f "${{ inputs.dockerfile }}" -t "${{ inputs.image_name }}:${{ inputs.tag }}" .

    - name: Tag with 'dev' if needed
      if: inputs.dev == 'true'
      shell: bash
      run: |
        echo "Tagging image with 'dev'"
        docker tag "${{ inputs.image_name }}:${{ inputs.tag }}" "${{ inputs.image_name }}:dev"

    # Only if "shouldRelease" is true, then we should fail if username/password are not provided
    - name: Ensure Docker username and password are provided
      if: inputs.shouldRelease == 'true'
      shell: bash
      run: |
        echo "Ensuring Docker username and password are provided when releasing the Docker image"
        if [ -z "${{ inputs.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME is required when shouldRelease is true"
          exit 1
        fi
        if [ -z "${{ inputs.DOCKER_PASSWORD }}" ]; then
          echo "DOCKER_PASSWORD is required when shouldRelease is true"
          exit 1
        fi

    # Login to Docker registry
    - name: Login to Docker registry
      if: inputs.shouldRelease == 'true'
      shell: bash
      run: echo "${{ inputs.DOCKER_PASSWORD }}" | docker login -u "${{ inputs.DOCKER_USERNAME }}" --password-stdin

    # Push the main tag
    - name: Push Docker image
      if: inputs.shouldRelease == 'true'
      shell: bash
      run: docker push "${{ inputs.image_name }}:${{ inputs.tag }}"

    # Push the 'dev' tag if needed
    - name: Push 'dev' tag
      if: inputs.shouldRelease == 'true' && inputs.dev == 'true'
      shell: bash
      run: docker push "${{ inputs.image_name }}:dev"
