name: "Build Docker Image"
description: "Build a Docker image for the specified Dockerfile"

inputs:
  dockerfile:
    description: "Path to the Dockerfile"
    required: true
  image_name:
    description: "Docker image name"
    required: true
  tag:
    description: "Tag to use for the Docker image"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Build Docker image
      run: docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.image_name }}:${{ inputs.tag }} .
