name: Sync Development to Main

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Setup SSH Keys and known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Fetch all branches
        run: |
          git fetch --all
          git fetch --tags

      - name: Update main branch
        run: |
          git checkout main
          git reset --hard origin/main
          git merge --ff-only origin/development
          git push origin main

      - name: Handle merge conflicts
        if: failure()
        run: |
          echo "⚠️  There was a conflict during the merge. Please resolve it manually."
          git merge --abort
          exit 1
